### ISSUE TITLE
Running MxNet 1.1.0 container

### ISSUE THREAD

**Issue by mklissa** [aws/sagemaker-mxnet-container#25]
Hi there,
when running the line:

 "docker build -t preprod-mxnet:1.1.0-cpu-py2 --build-arg py_version=2 --build-arg framework_installable=mxnet-1.1.0-py2.py3-none-manylinux1_x86_64.whl -f Dockerfile.cpu ." 

I get the following error:

COPY failed: stat /var/lib/docker/tmp/docker-builder295259424/mxnet-1.1.0-py2.py3-none-manylinux1_x86_64.whl: no such file or directory

Seems like a file is missing or I am missing a step to get the file at the right place?

Thanks

**Comment by winstonaws** [comment]
Yea, we're missing some explanation in the documentation. You need to download the file to your current directory from here: https://pypi.org/project/mxnet/1.1.0/#files

It's set up that way so that it can easily build using different MXNet binaries. However, we should change it so that by default it downloads that version for you. I'll see if I can get to that soon.

**Comment by juliensimon** [comment]
The next one is:

COPY failed: stat /var/lib/docker/tmp/docker-builder446864042/sagemaker_mxnet_container-1.0.0.tar.gz: no such file or directory

Where should this file come from? Is this related to https://github.com/aws/sagemaker-containers/tree/master/src/container_support ?

Could you please update the documentation? This is quite impossible to use at the moment :-/

**Comment by yangaws** [comment]
Hi,

The sagemaker_mxnet_container-1.0.0.tar.gz file can be produced by running

``python setup.py sdist``

And then this file will be in dist/

This is recorded in the README too 
https://github.com/aws/sagemaker-mxnet-container/blob/master/README.rst
